# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1to9-ON_fGt9z7p-gBGmXxHA6Z2TR7a8S
"""



import kagglehub

# Download latest version
path = kagglehub.dataset_download("risangbaskoro/wlasl-processed")

print("Path to dataset files:", path)



import os
import glob

# 1. Search your entire environment to find where WLASL_v0.3.json is located
print("Searching for WLASL_v0.3.json...")
found_paths = []
for root, dirs, files in os.walk("/content" if os.path.exists("/content") else "."):
    for file in files:
        if file.endswith(".json") and "WLASL" in file:
            found_paths.append(os.path.join(root, file))

if found_paths:
    print("Found JSON file at:", found_paths[0])
    DATASET_DIR = os.path.dirname(found_paths[0])
else:
    print("JSON file not found. Downloading directly...")
    import urllib.request
    DATASET_DIR = "./wlasl_data"
    os.makedirs(DATASET_DIR, exist_ok=True)
    json_path = os.path.join(DATASET_DIR, "WLASL_v0.3.json")
    url = "https://raw.githubusercontent.com/dxli94/WLASL/master/start_kit/WLASL_v0.3.json"
    urllib.request.urlretrieve(url, json_path)
    print(f"Downloaded to: {json_path}")

# 2. Get the list of json files from the verified path
json_files = glob.glob(os.path.join(DATASET_DIR, "*.json"))

if len(json_files) == 0:
    raise FileNotFoundError("No JSON file found inside WLASL dataset.")

print(f"Successfully loaded JSON file: {json_files[0]}")



import kagglehub
import os
import json
path = kagglehub.dataset_download("risangbaskoro/wlasl-processed")
print("Path:", path)
print("=" * 60)

for root, dirs, files in os.walk(path):
    level = root.replace(path, '').count(os.sep)
    indent = ' ' * 2 * level
    print(f'{indent} {os.path.basename(root)}/')
    subindent = ' ' * 2 * (level + 1)
    for i, file in enumerate(files[:10]):
        print(f'{subindent}📄 {file}')
    if len(files) > 10:
        print(f'{subindent}... و {len(files)-10} and other files')
    for file in files:
        if file.endswith('.json'):
            json_path = os.path.join(root, file)
            print(f'\n find fileJSON: {file}')
            with open(json_path, 'r') as f:
                try:
                    data = json.load(f)
                    if isinstance(data, list):
                        print(f'   number of operations {len(data)}')
                        if len(data) > 0:
                            print(f'  sample  {data[0]}')
                    elif isinstance(data, dict):
                        print(f'   keys {list(data.keys())[:5]}')
                except:
                    print(' can not the file   ')



import kagglehub
path = kagglehub.dataset_download("risangbaskoro/wlasl-processed")
print("Path to dataset files:", path)

import kagglehub
path = kagglehub.dataset_download("risangbaskoro/wlasl-processed")
print(repr(path))

import os

print("Does /kaggle/input/wlasl-processed exist?", os.path.exists("/kaggle/input/wlasl-processed"))

# Check the real kagglehub cache location
cache_dir = os.path.expanduser("~/.cache/kagglehub/datasets")
print("\nDoes kagglehub cache exist?", os.path.exists(cache_dir))
if os.path.exists(cache_dir):
    for root, dirs, files in os.walk(cache_dir):
        depth = root.replace(cache_dir, "").count(os.sep)
        if depth > 4:
            dirs[:] = []
            continue
        print(root)

import os

for root, dirs, files in os.walk("/kaggle/input/wlasl-processed"):
    depth = root.replace("/kaggle/input/wlasl-processed", "").count(os.sep)
    if depth > 2:
        dirs[:] = []
        continue
    print(root, "->", len(files), "files", files[:3] if files else "")

!pip -q install kagglehub opencv-python-headless tqdm scikit-learn decord


# ============================================================
# 2) IMPORTS
# ============================================================

import os
import json
import glob
import copy
import random
import warnings

warnings.filterwarnings("ignore")

import cv2
import numpy as np

import kagglehub

try:
    from decord import VideoReader, cpu as decord_cpu
    HAS_DECORD = True
except ImportError:
    HAS_DECORD = False
    print("Decord unavailable - using OpenCV")

import matplotlib.pyplot as plt

from tqdm.auto import tqdm
from collections import Counter

import torch
import torch.nn as nn
import torch.optim as optim

from torch.utils.data import (
    Dataset,
    DataLoader
)

from torchvision.models.video import (
    r3d_18,
    R3D_18_Weights
)

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report,
    accuracy_score
)


# ============================================================
# 3) SETTINGS
# ============================================================

NUM_CLASSES_TARGET = 100

MIN_SAMPLES_PER_CLASS = 4

# ------------------------------------------------------------
# Video settings
# ------------------------------------------------------------

NUM_FRAMES = 24
IMG_SIZE = 112

# Smaller batch because NUM_FRAMES increased
BATCH_SIZE = 8


# ------------------------------------------------------------
# Training
# ------------------------------------------------------------

WARMUP_EPOCHS = 10

FINETUNE_EPOCHS = 40

FT_WARMUP_EPOCHS = 5


# ------------------------------------------------------------
# Learning rates
# ------------------------------------------------------------

LR_HEAD = 3e-4

LR_BACKBONE = 1e-5


# ------------------------------------------------------------
# Regularization
# ------------------------------------------------------------

WEIGHT_DECAY = 1e-4

LABEL_SMOOTHING = 0.0


# ------------------------------------------------------------
# Mixup DISABLED for this experiment
# ------------------------------------------------------------

MIXUP_ALPHA = 0.0

MIXUP_PROB = 0.0


# ------------------------------------------------------------
# EMA
# ------------------------------------------------------------

EMA_DECAY = 0.999


# ------------------------------------------------------------
# Test Time Augmentation
# ------------------------------------------------------------

TTA_CLIPS = 3


# ------------------------------------------------------------
# Early stopping
# ------------------------------------------------------------

PATIENCE = 10


# ------------------------------------------------------------
# Workers
# ------------------------------------------------------------

NUM_WORKERS = min(
    4,
    os.cpu_count() or 2
)


# ------------------------------------------------------------
# Seed
# ------------------------------------------------------------

SEED = 42


# ============================================================
# 4) SAFE MODEL SAVE DIRECTORY
# ============================================================

if os.path.exists("/kaggle"):
    SAVE_DIR = "/kaggle/working"
else:
    SAVE_DIR = "/content"

os.makedirs(
    SAVE_DIR,
    exist_ok=True
)

BEST_MODEL_PATH = os.path.join(
    SAVE_DIR,
    "BEST_WLASL_3DCNN.pth"
)

print("=" * 80)
print("MODEL SAVE DIRECTORY:")
print(SAVE_DIR)

print(
    "BEST MODEL PATH:"
)

print(
    BEST_MODEL_PATH
)

print("=" * 80)


# ============================================================
# 5) DEVICE
# ============================================================

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("=" * 80)

print(
    "DEVICE:",
    DEVICE
)

if torch.cuda.is_available():

    print(
        "GPU:",
        torch.cuda.get_device_name(0)
    )

    print(
        "CUDA:",
        torch.version.cuda
    )

    torch.backends.cudnn.benchmark = True

else:

    print(
        "WARNING: GPU is NOT enabled."
    )

print("=" * 80)


# ============================================================
# 6) SEED
# ============================================================

random.seed(SEED)

np.random.seed(SEED)

torch.manual_seed(SEED)

if torch.cuda.is_available():

    torch.cuda.manual_seed_all(SEED)


# ============================================================
# 7) DOWNLOAD WLASL DATASET
# ============================================================

print(
    "\n" + "=" * 80
)

print(
    "DOWNLOADING / LOCATING WLASL DATASET"
)

print(
    "=" * 80
)

DATA_ROOT = kagglehub.dataset_download(
    "risangbaskoro/wlasl-processed"
)

print(
    "Dataset path:",
    DATA_ROOT
)


# ============================================================
# 8) FIND VIDEO FILES
# ============================================================

video_files = []

for root, dirs, files in os.walk(
    DATA_ROOT
):

    for file in files:

        if file.lower().endswith(
            (
                ".mp4",
                ".avi",
                ".mov",
                ".mkv"
            )
        ):

            video_files.append(
                os.path.join(
                    root,
                    file
                )
            )


print(
    f"\nFound {len(video_files)} video files"
)

if len(video_files) == 0:

    raise FileNotFoundError(
        "No video files were found inside the downloaded WLASL dataset."
    )


# ============================================================
# 9) VIDEO LOOKUP
# ============================================================

video_lookup = {}

for video_path in video_files:

    video_id = os.path.splitext(
        os.path.basename(
            video_path
        )
    )[0]

    video_lookup[
        video_id
    ] = video_path


# ============================================================
# 10) FIND WLASL JSON
# ============================================================

json_files = glob.glob(
    os.path.join(
        DATA_ROOT,
        "**",
        "*.json"
    ),
    recursive=True
)

JSON_PATH = None

for f in json_files:

    filename = os.path.basename(
        f
    ).lower()

    if "wlasl" in filename:

        JSON_PATH = f

        break


if JSON_PATH is None and json_files:

    JSON_PATH = json_files[0]


if JSON_PATH is None:

    raise FileNotFoundError(
        "WLASL JSON annotation file was not found."
    )


print(
    "\nJSON:",
    JSON_PATH
)


# ============================================================
# 11) LOAD JSON ANNOTATIONS
# ============================================================

with open(
    JSON_PATH,
    "r",
    encoding="utf-8"
) as f:

    annotations = json.load(f)


# ============================================================
# 12) BUILD RECORDS
# ============================================================

records = []

for item in annotations:

    if not isinstance(
        item,
        dict
    ):

        continue

    gloss = item.get(
        "gloss"
    )

    if gloss is None:

        continue

    for instance in item.get(
        "instances",
        []
    ):

        video_id = str(
            instance.get(
                "video_id",
                ""
            )
        )

        if video_id not in video_lookup:

            continue

        split = instance.get(
            "split",
            "train"
        )

        records.append(
            {
                "video_id": video_id,

                "gloss": gloss,

                "video_path":
                    video_lookup[
                        video_id
                    ],

                "split": split
            }
        )


print(
    "\nMatched records:",
    len(records)
)

if len(records) == 0:

    raise RuntimeError(
        "No videos matched the WLASL annotations."
    )


# ============================================================
# 13) CLASS SELECTION
# ============================================================

class_counts = Counter(
    r["gloss"]
    for r in records
)


valid_classes = [
    cls
    for cls, count
    in class_counts.items()
    if count >= MIN_SAMPLES_PER_CLASS
]


# ------------------------------------------------------------
# Prefer classes that have enough TRAIN samples
# ------------------------------------------------------------

train_class_counts = Counter(
    r["gloss"]
    for r in records
    if r["split"] == "train"
)


valid_classes = [
    cls
    for cls in valid_classes
    if train_class_counts.get(
        cls,
        0
    ) >= 2
]


# ------------------------------------------------------------
# Select most frequent classes
# ------------------------------------------------------------

selected_classes = [
    cls
    for cls, _
    in train_class_counts.most_common()
    if cls in valid_classes
][:NUM_CLASSES_TARGET]


NUM_CLASSES = len(
    selected_classes
)


class_to_idx = {
    cls: i
    for i, cls
    in enumerate(
        selected_classes
    )
}


idx_to_class = {
    i: cls
    for cls, i
    in class_to_idx.items()
}


# ------------------------------------------------------------
# Keep only selected classes
# ------------------------------------------------------------

records = [
    r
    for r in records
    if r["gloss"] in class_to_idx
]


print(
    "\nUsing classes:",
    NUM_CLASSES
)

print(
    "Total videos:",
    len(records)
)

print(
    "\nFirst classes:"
)

print(
    selected_classes[:20]
)


# ============================================================
# 14) OFFICIAL TRAIN / VAL / TEST SPLIT
# ============================================================

train_records = [
    r
    for r in records
    if r["split"] == "train"
]


val_records = [
    r
    for r in records
    if r["split"] in [
        "val",
        "validation"
    ]
]


test_records = [
    r
    for r in records
    if r["split"] == "test"
]


# ============================================================
# 15) FALLBACK SPLIT ONLY IF NEEDED
# ============================================================

if (
    len(train_records) == 0
    or len(val_records) == 0
    or len(test_records) == 0
):

    print(
        "\nOfficial split incomplete."
    )

    print(
        "Creating stratified Train / Validation / Test split..."
    )

    labels = [
        r["gloss"]
        for r in records
    ]

    indices = np.arange(
        len(records)
    )


    train_val_idx, test_idx = train_test_split(

        indices,

        test_size=0.20,

        stratify=labels,

        random_state=SEED
    )


    train_val_labels = [
        labels[i]
        for i in train_val_idx
    ]


    train_idx, val_idx = train_test_split(

        train_val_idx,

        test_size=0.15,

        stratify=train_val_labels,

        random_state=SEED
    )


    train_records = [
        records[i]
        for i in train_idx
    ]


    val_records = [
        records[i]
        for i in val_idx
    ]


    test_records = [
        records[i]
        for i in test_idx
    ]


print(
    "\n" + "=" * 80
)

print(
    "FINAL DATA SPLIT"
)

print(
    "=" * 80
)

print(
    "TRAIN:",
    len(train_records)
)

print(
    "VALIDATION:",
    len(val_records)
)

print(
    "TEST:",
    len(test_records)
)


# ============================================================
# 16) CHECK CLASS DISTRIBUTION
# ============================================================

print(
    "\n" + "=" * 80
)

print(
    "CLASS DISTRIBUTION CHECK"
)

print(
    "=" * 80
)


train_counts_selected = Counter(
    r["gloss"]
    for r in train_records
)


print(
    "\n20 classes with FEWEST training samples:"
)

print(
    sorted(
        train_counts_selected.items(),
        key=lambda x: x[1]
    )[:20]
)


print(
    "\n20 classes with MOST training samples:"
)

print(
    sorted(
        train_counts_selected.items(),
        key=lambda x: x[1],
        reverse=True
    )[:20]
)


# ============================================================
# 17) VIDEO READING
# ============================================================

MEAN = np.array(
    [
        0.43216,
        0.394666,
        0.37645
    ],
    dtype=np.float32
)


STD = np.array(
    [
        0.22803,
        0.22145,
        0.216989
    ],
    dtype=np.float32
)


def _read_frames_cv2(
    path,
    indices
):

    cap = cv2.VideoCapture(
        path
    )

    frames = []


    for idx in indices:

        cap.set(
            cv2.CAP_PROP_POS_FRAMES,
            int(idx)
        )

        ret, frame = cap.read()


        if not ret:

            frame = np.zeros(
                (
                    IMG_SIZE,
                    IMG_SIZE,
                    3
                ),
                dtype=np.uint8
            )

        else:

            frame = cv2.cvtColor(
                frame,
                cv2.COLOR_BGR2RGB
            )


        frames.append(
            frame
        )


    cap.release()


    return np.asarray(
        frames
    )


# ============================================================
# 18) GET VIDEO LENGTH
# ============================================================

def _get_reader_and_length(
    path
):

    if HAS_DECORD:

        try:

            vr = VideoReader(
                path,
                ctx=decord_cpu(0),
                num_threads=1
            )

            return (
                len(vr),
                vr
            )

        except Exception:

            pass


    cap = cv2.VideoCapture(
        path
    )

    total = int(
        cap.get(
            cv2.CAP_PROP_FRAME_COUNT
        )
    )

    cap.release()


    return (
        total,
        None
    )


# ============================================================
# 19) CONSISTENT TEMPORAL + SPATIAL AUGMENTATION
# ============================================================

def augment_clip(
    frames
):

    h, w, _ = frames[0].shape


    # --------------------------------------------------------
    # Random spatial crop
    # --------------------------------------------------------

    if random.random() < 0.8:

        scale = random.uniform(
            0.80,
            1.0
        )


        crop_h = max(
            int(h * scale),
            1
        )


        crop_w = max(
            int(w * scale),
            1
        )


        if (
            crop_h <= h
            and crop_w <= w
        ):

            y0 = random.randint(
                0,
                h - crop_h
            )


            x0 = random.randint(
                0,
                w - crop_w
            )


            frames = np.stack([

                cv2.resize(
                    f[
                        y0:y0 + crop_h,
                        x0:x0 + crop_w
                    ],

                    (
                        IMG_SIZE,
                        IMG_SIZE
                    )
                )

                for f in frames
            ])


        else:

            frames = np.stack([

                cv2.resize(
                    f,
                    (
                        IMG_SIZE,
                        IMG_SIZE
                    )
                )

                for f in frames
            ])


    else:

        frames = np.stack([

            cv2.resize(
                f,
                (
                    IMG_SIZE,
                    IMG_SIZE
                )
            )

            for f in frames
        ])


    # --------------------------------------------------------
    # Brightness / Contrast
    # Same transformation across whole video
    # --------------------------------------------------------

    if random.random() < 0.5:

        brightness = random.uniform(
            0.85,
            1.15
        )


        contrast = random.uniform(
            0.85,
            1.15
        )


        frames = frames.astype(
            np.float32
        )


        mean = frames.mean(
            axis=(1, 2),
            keepdims=True
        )


        frames = (
            (frames - mean)
            * contrast
            + mean
        )


        frames *= brightness


    return np.clip(
        frames,
        0,
        255
    )


# ============================================================
# 20) LOAD VIDEO
# ============================================================

def load_video(
    path,
    train=False,
    start_override=None
):

    total_frames, vr = (
        _get_reader_and_length(
            path
        )
    )


    if total_frames <= 0:

        return torch.zeros(
            3,
            NUM_FRAMES,
            IMG_SIZE,
            IMG_SIZE
        )


    # ========================================================
    # Temporal Sampling
    # ========================================================

    if (
        start_override is not None
        and total_frames > NUM_FRAMES
    ):

        start = min(
            start_override,
            total_frames - NUM_FRAMES
        )


        indices = np.linspace(

            start,

            start + NUM_FRAMES - 1,

            NUM_FRAMES

        ).astype(int)


    elif (
        train
        and total_frames > NUM_FRAMES
    ):

        max_start = (
            total_frames
            - NUM_FRAMES
        )


        start = random.randint(
            0,
            max_start
        )


        indices = np.linspace(

            start,

            start + NUM_FRAMES - 1,

            NUM_FRAMES

        ).astype(int)


    else:

        # For validation/test
        # sample uniformly across entire video

        indices = np.linspace(

            0,

            total_frames - 1,

            NUM_FRAMES

        ).astype(int)


    indices = np.clip(

        indices,

        0,

        total_frames - 1

    )


    # ========================================================
    # Read Frames
    # ========================================================

    raw_frames = None


    if vr is not None:

        try:

            raw_frames = (

                vr.get_batch(
                    indices
                ).asnumpy()

            )

        except Exception:

            raw_frames = None


    if raw_frames is None:

        raw_frames = _read_frames_cv2(

            path,

            indices

        )


    frames = raw_frames


    # ========================================================
    # Augmentation
    # ========================================================

    if train:

        frames = augment_clip(
            frames
        )

    else:

        frames = np.stack([

            cv2.resize(
                f,
                (
                    IMG_SIZE,
                    IMG_SIZE
                )
            )

            for f in frames

        ])


    # ========================================================
    # Normalize
    # ========================================================

    frames = frames.astype(
        np.float32
    )


    frames /= 255.0


    frames = (
        frames - MEAN
    ) / STD


    # ========================================================
    # T,H,W,C -> C,T,H,W
    # ========================================================

    frames = np.transpose(

        frames,

        (
            3,
            0,
            1,
            2
        )

    )


    return torch.tensor(

        frames,

        dtype=torch.float32

    )


# ============================================================
# 21) DATASET
# ============================================================

class WLASLDataset(
    Dataset
):

    def __init__(
        self,
        records,
        class_to_idx,
        train=False
    ):

        self.records = records

        self.class_to_idx = class_to_idx

        self.train = train


    def __len__(self):

        return len(
            self.records
        )


    def __getitem__(
        self,
        index
    ):

        record = self.records[
            index
        ]


        video = load_video(

            record["video_path"],

            train=self.train

        )


        label = self.class_to_idx[

            record["gloss"]

        ]


        return (

            video,

            torch.tensor(
                label,
                dtype=torch.long
            )

        )


# ============================================================
# 22) DATASETS
# ============================================================

train_dataset = WLASLDataset(

    train_records,

    class_to_idx,

    train=True

)


val_dataset = WLASLDataset(

    val_records,

    class_to_idx,

    train=False

)


test_dataset = WLASLDataset(

    test_records,

    class_to_idx,

    train=False

)


# ============================================================
# 23) DATALOADERS
# ============================================================
#
# IMPORTANT:
# We removed WeightedRandomSampler for this experiment.
#
# We use normal shuffle=True.
#
# ============================================================

loader_kwargs = {

    "num_workers":
        NUM_WORKERS,

    "pin_memory":
        torch.cuda.is_available(),

    "persistent_workers":
        (
            NUM_WORKERS > 0
        )
}


train_loader = DataLoader(

    train_dataset,

    batch_size=BATCH_SIZE,

    shuffle=True,

    **loader_kwargs

)


val_loader = DataLoader(

    val_dataset,

    batch_size=BATCH_SIZE,

    shuffle=False,

    **loader_kwargs

)


test_loader = DataLoader(

    test_dataset,

    batch_size=BATCH_SIZE,

    shuffle=False,

    **loader_kwargs

)


# ============================================================
# 24) MODEL — PRETRAINED R3D-18
# ============================================================

print(
    "\nLoading pretrained R3D-18..."
)


backbone = r3d_18(

    weights=R3D_18_Weights.DEFAULT

)


in_features = (
    backbone.fc.in_features
)


backbone.fc = nn.Identity()


# ============================================================
# 25) IMPROVED CLASSIFIER
# ============================================================

class SignClassifier(
    nn.Module
):

    def __init__(
        self,
        input_dim,
        num_classes
    ):

        super().__init__()


        self.network = nn.Sequential(

            nn.Linear(
                input_dim,
                512
            ),

            nn.BatchNorm1d(
                512
            ),

            nn.ReLU(
                inplace=True
            ),

            nn.Dropout(
                0.25
            ),


            nn.Linear(
                512,
                256
            ),

            nn.ReLU(
                inplace=True
            ),

            nn.Dropout(
                0.15
            ),


            nn.Linear(
                256,
                num_classes
            )

        )


    def forward(
        self,
        x
    ):

        return self.network(
            x
        )


# ============================================================
# 26) COMPLETE MODEL
# ============================================================

class WLASL3DCNN(
    nn.Module
):

    def __init__(
        self,
        num_classes
    ):

        super().__init__()


        self.backbone = backbone


        self.classifier = SignClassifier(

            in_features,

            num_classes

        )


    def forward(
        self,
        x
    ):

        features = self.backbone(
            x
        )


        return self.classifier(
            features
        )


model = WLASL3DCNN(
    NUM_CLASSES
).to(
    DEVICE
)


print(
    "Model parameters:",
    sum(
        p.numel()
        for p in model.parameters()
    )
)


# ============================================================
# 27) EMA
# ============================================================

class ModelEma:

    def __init__(
        self,
        model,
        decay=EMA_DECAY
    ):

        self.ema = copy.deepcopy(
            model
        ).eval()


        for p in self.ema.parameters():

            p.requires_grad_(False)


        self.decay = decay

        self.updates = 0


    @torch.no_grad()
    def update(
        self,
        model
    ):

        self.updates += 1


        d = min(

            self.decay,

            (
                self.updates + 1
            )
            /
            (
                self.updates + 10
            )

        )


        model_state = (
            model.state_dict()
        )


        for k, v in self.ema.state_dict().items():

            if v.dtype.is_floating_point:

                v.copy_(

                    v * d

                    +

                    (
                        1 - d
                    )

                    *

                    model_state[
                        k
                    ].detach()

                )

            else:

                v.copy_(
                    model_state[k]
                )


ema = ModelEma(
    model
)


# ============================================================
# 28) MIXUP
# ============================================================
#
# Disabled in this experiment.
#
# Functions kept here so the training function remains
# compatible if you want to enable Mixup later.
#
# ============================================================

def mixup_batch(
    x,
    y,
    alpha=MIXUP_ALPHA
):

    if alpha <= 0:

        return (
            x,
            y,
            y,
            1.0
        )


    lam = float(

        np.random.beta(
            alpha,
            alpha
        )

    )


    index = torch.randperm(

        x.size(0),

        device=x.device

    )


    mixed_x = (

        lam * x

        +

        (1 - lam)
        * x[index]

    )


    return (

        mixed_x,

        y,

        y[index],

        lam

    )


def mixup_loss(
    criterion,
    outputs,
    y_a,
    y_b,
    lam
):

    return (

        lam

        *

        criterion(
            outputs,
            y_a
        )

        +

        (1 - lam)

        *

        criterion(
            outputs,
            y_b
        )

    )


# ============================================================
# 29) LOSS
# ============================================================

criterion = nn.CrossEntropyLoss(

    label_smoothing=LABEL_SMOOTHING

)


# ============================================================
# 30) PHASE 1 — FREEZE BACKBONE
# ============================================================

for p in model.backbone.parameters():

    p.requires_grad = False


for p in model.classifier.parameters():

    p.requires_grad = True


# ------------------------------------------------------------
# Head optimizer
# ------------------------------------------------------------

optimizer = optim.AdamW(

    model.classifier.parameters(),

    lr=LR_HEAD,

    weight_decay=WEIGHT_DECAY

)


# ============================================================
# 31) AMP
# ============================================================

use_amp = torch.cuda.is_available()


scaler = torch.amp.GradScaler(

    "cuda",

    enabled=use_amp

)


# ============================================================
# 32) TRAIN ONE EPOCH
# ============================================================

def train_epoch():

    model.train()


    total_loss = 0.0

    correct = 0

    total = 0


    pbar = tqdm(

        train_loader,

        desc="Training"

    )


    for videos, labels in pbar:

        videos = videos.to(

            DEVICE,

            non_blocking=True

        )


        labels = labels.to(

            DEVICE,

            non_blocking=True

        )


        # ----------------------------------------------------
        # Mixup disabled
        # ----------------------------------------------------

        do_mixup = (

            MIXUP_ALPHA > 0

            and random.random()
            < MIXUP_PROB

        )


        if do_mixup:

            videos, y_a, y_b, lam = (

                mixup_batch(

                    videos,

                    labels

                )

            )


        optimizer.zero_grad(

            set_to_none=True

        )


        # ----------------------------------------------------
        # Forward
        # ----------------------------------------------------

        with torch.amp.autocast(

            "cuda",

            enabled=use_amp

        ):

            outputs = model(
                videos
            )


            if do_mixup:

                loss = mixup_loss(

                    criterion,

                    outputs,

                    y_a,

                    y_b,

                    lam

                )

            else:

                loss = criterion(

                    outputs,

                    labels

                )


        # ----------------------------------------------------
        # Backward
        # ----------------------------------------------------

        scaler.scale(
            loss
        ).backward()


        scaler.unscale_(
            optimizer
        )


        torch.nn.utils.clip_grad_norm_(

            model.parameters(),

            1.0

        )


        scaler.step(
            optimizer
        )


        scaler.update()


        # ----------------------------------------------------
        # EMA
        # ----------------------------------------------------

        ema.update(
            model
        )


        # ----------------------------------------------------
        # Metrics
        # ----------------------------------------------------

        total_loss += (

            loss.item()

            *

            labels.size(0)

        )


        pred = outputs.argmax(
            dim=1
        )


        correct += (

            pred == labels

        ).sum().item()


        total += labels.size(0)


        pbar.set_postfix(

            loss=f"{loss.item():.3f}",

            acc=f"{correct / max(total, 1) * 100:.2f}%"

        )


    return (

        total_loss
        /
        max(
            1,
            total
        ),

        correct
        /
        max(
            1,
            total
        )

    )


# ============================================================
# 33) VALIDATION
# ============================================================

@torch.no_grad()
def validate(
    eval_model
):

    eval_model.eval()


    total_loss = 0.0

    correct = 0

    total = 0


    for videos, labels in tqdm(

        val_loader,

        desc="Validation",

        leave=False

    ):

        videos = videos.to(

            DEVICE,

            non_blocking=True

        )


        labels = labels.to(

            DEVICE,

            non_blocking=True

        )


        # --------------------------------------------------------
        # Validation TTA
        # Original + temporal reverse + horizontal flip
        # --------------------------------------------------------

        val_views = [
            videos,
            torch.flip(videos, dims=[2]),
            torch.flip(videos, dims=[4])
        ]


        outputs_sum = None


        with torch.amp.autocast(

            "cuda",

            enabled=use_amp

        ):

            for view in val_views:

                view_outputs = eval_model(
                    view
                )


                if outputs_sum is None:

                    outputs_sum = view_outputs

                else:

                    outputs_sum += view_outputs


            outputs = (

                outputs_sum
                /
                len(val_views)

            )


            loss = criterion(

                outputs,

                labels

            )


        total_loss += (

            loss.item()

            *

            labels.size(0)

        )


        pred = outputs.argmax(
            dim=1
        )


        correct += (

            pred == labels

        ).sum().item()


        total += labels.size(0)


    return (

        total_loss
        /
        max(
            1,
            total
        ),

        correct
        /
        max(
            1,
            total
        )

    )


# ============================================================

# 34) HISTORY
# ============================================================

history = {

    "train_loss": [],

    "train_acc": [],

    "val_loss": [],

    "val_acc": []

}


best_val = 0.0

bad_epochs = 0


# ============================================================
# 35) PHASE 1 — CLASSIFIER WARMUP
# ============================================================

print(
    "\n" + "=" * 80
)

print(
    "PHASE 1 — CLASSIFIER WARMUP"
)

print(
    "=" * 80
)


for epoch in range(
    WARMUP_EPOCHS
):

    train_loss, train_acc = (

        train_epoch()

    )


    raw_val_loss, raw_val_acc = (

        validate(
            model
        )

    )


    ema_val_loss, ema_val_acc = (

        validate(
            ema.ema
        )

    )


    # --------------------------------------------------------
    # Select better model
    # --------------------------------------------------------

    if ema_val_acc >= raw_val_acc:

        val_acc = ema_val_acc

        best_is_ema = True

    else:

        val_acc = raw_val_acc

        best_is_ema = False


    # --------------------------------------------------------
    # History
    # --------------------------------------------------------

    history[
        "train_loss"
    ].append(
        train_loss
    )


    history[
        "train_acc"
    ].append(
        train_acc
    )


    history[
        "val_loss"
    ].append(

        min(
            raw_val_loss,
            ema_val_loss
        )

    )


    history[
        "val_acc"
    ].append(
        val_acc
    )


    # --------------------------------------------------------
    # Print
    # --------------------------------------------------------

    print(
        f"\nEpoch "
        f"{epoch + 1}/{WARMUP_EPOCHS}"
    )


    print(
        f"Train Accuracy: "
        f"{train_acc * 100:.2f}%"
    )


    print(
        f"Val Accuracy RAW: "
        f"{raw_val_acc * 100:.2f}%"
    )


    print(
        f"Val Accuracy EMA: "
        f"{ema_val_acc * 100:.2f}%"
    )


    # --------------------------------------------------------
    # Save best
    # --------------------------------------------------------

    if val_acc > best_val:

        best_val = val_acc

        bad_epochs = 0


        torch.save(

            {

                "model":
                    model.state_dict(),

                "ema":
                    ema.ema.state_dict(),

                "best_is_ema":
                    best_is_ema,

                "class_to_idx":
                    class_to_idx,

                "idx_to_class":
                    idx_to_class,

                "num_classes":
                    NUM_CLASSES

            },

            BEST_MODEL_PATH

        )


        print(
            "🔥 BEST MODEL SAVED"
        )


    else:

        bad_epochs += 1


# ============================================================
# 36) PHASE 2 — FINE-TUNING
# ============================================================

print(
    "\n" + "=" * 80
)

print(
    "PHASE 2 — FINE-TUNING R3D-18"
)

print(
    "=" * 80
)


# ============================================================
# Freeze EVERYTHING first
# ============================================================

for p in model.backbone.parameters():

    p.requires_grad = False


# ============================================================
# Unfreeze layer2
# ============================================================

for p in model.backbone.layer2.parameters():

    p.requires_grad = True


# ============================================================
# Unfreeze layer3
# ============================================================

for p in model.backbone.layer3.parameters():

    p.requires_grad = True


# ============================================================
# Unfreeze layer4
# ============================================================

for p in model.backbone.layer4.parameters():

    p.requires_grad = True


# ============================================================
# Classifier trainable
# ============================================================

for p in model.classifier.parameters():

    p.requires_grad = True


# ============================================================
# 37) OPTIMIZER
# ============================================================

optimizer = optim.AdamW(

    [

        # Layer 2
        {
            "params":
                model.backbone.layer2.parameters(),

            "lr":
                5e-6
        },


        # Layer 3
        {
            "params":
                model.backbone.layer3.parameters(),

            "lr":
                1e-5
        },


        # Layer 4
        {
            "params":
                model.backbone.layer4.parameters(),

            "lr":
                1.5e-5
        },


        # Classifier
        {
            "params":
                model.classifier.parameters(),

            "lr":
                LR_HEAD
        }

    ],

    weight_decay=WEIGHT_DECAY

)


# ============================================================
# 38) LR SCHEDULER
# ============================================================

warmup_sched = optim.lr_scheduler.LinearLR(

    optimizer,

    start_factor=0.1,

    total_iters=FT_WARMUP_EPOCHS

)


cosine_sched = optim.lr_scheduler.CosineAnnealingLR(

    optimizer,

    T_max=max(

        1,

        FINETUNE_EPOCHS
        -
        FT_WARMUP_EPOCHS

    )

)


scheduler = optim.lr_scheduler.SequentialLR(

    optimizer,

    schedulers=[

        warmup_sched,

        cosine_sched

    ],

    milestones=[

        FT_WARMUP_EPOCHS

    ]

)


# ============================================================
# 39) FINE-TUNING LOOP
# ============================================================

for epoch in range(

    FINETUNE_EPOCHS

):

    train_loss, train_acc = (

        train_epoch()

    )


    raw_val_loss, raw_val_acc = (

        validate(
            model
        )

    )


    ema_val_loss, ema_val_acc = (

        validate(
            ema.ema
        )

    )


    scheduler.step()


    # --------------------------------------------------------
    # Select best evaluation model
    # --------------------------------------------------------

    if ema_val_acc >= raw_val_acc:

        val_acc = ema_val_acc

        best_is_ema = True

    else:

        val_acc = raw_val_acc

        best_is_ema = False


    # --------------------------------------------------------
    # History
    # --------------------------------------------------------

    history[
        "train_loss"
    ].append(
        train_loss
    )


    history[
        "train_acc"
    ].append(
        train_acc
    )


    history[
        "val_loss"
    ].append(

        min(
            raw_val_loss,
            ema_val_loss
        )

    )


    history[
        "val_acc"
    ].append(
        val_acc
    )


    # --------------------------------------------------------
    # Current LR
    # --------------------------------------------------------

    current_lrs = [
        group["lr"]
        for group in optimizer.param_groups
    ]


    # --------------------------------------------------------
    # Print
    # --------------------------------------------------------

    print(
        f"\nFine-tune Epoch "
        f"{epoch + 1}/{FINETUNE_EPOCHS}"
    )


    print(
        f"Train Accuracy: "
        f"{train_acc * 100:.2f}%"
    )


    print(
        f"Val Accuracy RAW: "
        f"{raw_val_acc * 100:.2f}%"
    )


    print(
        f"Val Accuracy EMA: "
        f"{ema_val_acc * 100:.2f}%"
    )


    print(
        "Learning Rates:",
        [
            f"{lr:.2e}"
            for lr in current_lrs
        ]
    )


    # --------------------------------------------------------
    # Save best model
    # --------------------------------------------------------

    if val_acc > best_val:

        best_val = val_acc

        bad_epochs = 0


        torch.save(

            {

                "model":
                    model.state_dict(),

                "ema":
                    ema.ema.state_dict(),

                "best_is_ema":
                    best_is_ema,

                "class_to_idx":
                    class_to_idx,

                "idx_to_class":
                    idx_to_class,

                "num_classes":
                    NUM_CLASSES

            },

            BEST_MODEL_PATH

        )


        print(
            "🔥 BEST MODEL SAVED"
        )


    else:

        bad_epochs += 1


        print(
            "No improvement:",
            bad_epochs,
            "/",
            PATIENCE
        )


    # --------------------------------------------------------
    # Early stopping
    # --------------------------------------------------------

    if bad_epochs >= PATIENCE:

        print(
            "\nEarly stopping."
        )

        break


# ============================================================
# 40) LOAD BEST MODEL
# ============================================================

print(
    "\n" + "=" * 80
)

print(
    "LOADING BEST MODEL"
)

print(
    "=" * 80
)


if not os.path.exists(
    BEST_MODEL_PATH
):

    raise FileNotFoundError(

        f"Best model was not saved at: "
        f"{BEST_MODEL_PATH}"

    )


checkpoint = torch.load(

    BEST_MODEL_PATH,

    map_location=DEVICE

)


# ============================================================
# Create evaluation model
# ============================================================

eval_model = WLASL3DCNN(

    NUM_CLASSES

).to(
    DEVICE
)


# ============================================================
# Load EMA or RAW
# ============================================================

if checkpoint.get(

    "best_is_ema",

    True

):

    eval_model.load_state_dict(

        checkpoint["ema"]

    )


    print(
        "Using EMA model."
    )


else:

    eval_model.load_state_dict(

        checkpoint["model"]

    )


    print(
        "Using RAW model."
    )


eval_model.eval()


# ============================================================
# 41) TTA
# ============================================================

@torch.no_grad()
def predict_probs_tta(

    video_path,

    n_clips=TTA_CLIPS

):

    total_frames, _ = (

        _get_reader_and_length(

            video_path

        )

    )


    # --------------------------------------------------------
    # Select multiple temporal clips
    # --------------------------------------------------------

    if (

        total_frames > NUM_FRAMES

        and

        n_clips > 1

    ):

        starts = np.linspace(

            0,

            max(

                1,

                total_frames
                -
                NUM_FRAMES

            ),

            n_clips

        ).astype(int)


    else:

        starts = [0]


    probs_sum = None


    # ========================================================
    # Predict every clip
    # ========================================================

    for start in starts:

        clip = load_video(

            video_path,

            train=False,

            start_override=int(
                start
            )

        )


        clip = clip.unsqueeze(
            0
        ).to(

            DEVICE,

            non_blocking=True

        )


        with torch.amp.autocast(

            "cuda",

            enabled=use_amp

        ):

            output = eval_model(

                clip

            )


        probs = torch.softmax(

            output.float(),

            dim=1

        )


        if probs_sum is None:

            probs_sum = probs

        else:

            probs_sum += probs


    # Average predictions
    return (

        probs_sum
        /
        len(starts)

    ).squeeze(0)


# ============================================================
# 42) TEST
# ============================================================

@torch.no_grad()
def test_model():

    correct = 0

    total = 0


    y_true = []

    y_pred = []


    for record in tqdm(

        test_records,

        desc="Testing with TTA"

    ):

        label = class_to_idx[

            record["gloss"]

        ]


        probs = predict_probs_tta(

            record["video_path"]

        )


        pred = (

            probs.argmax().item()

        )


        correct += int(

            pred == label

        )


        total += 1


        y_true.append(
            label
        )


        y_pred.append(
            pred
        )


    accuracy = (

        correct

        /

        max(
            1,
            total
        )

    )


    return (

        accuracy,

        y_true,

        y_pred

    )


test_acc, y_true, y_pred = (

    test_model()

)


# ============================================================
# 43) TOP-5 ACCURACY
# ============================================================

@torch.no_grad()
def top5_accuracy():

    correct = 0

    total = 0


    for record in tqdm(

        test_records,

        desc="Top-5"

    ):

        label = class_to_idx[

            record["gloss"]

        ]


        probs = predict_probs_tta(

            record["video_path"]

        )


        top5 = torch.topk(

            probs,

            k=min(

                5,

                NUM_CLASSES

            )

        ).indices


        correct += int(

            label in top5

        )


        total += 1


    return (

        correct

        /

        max(
            1,
            total
        )

    )


top5 = top5_accuracy()


# ============================================================
# 44) FINAL RESULTS
# ============================================================

print(
    "\n" + "=" * 80
)

print(
    "FINAL RESULTS"
)

print(
    "=" * 80
)


print(

    f"BEST VALIDATION ACCURACY: "
    f"{best_val * 100:.2f}%"

)


print(

    f"TEST TOP-1 ACCURACY: "
    f"{test_acc * 100:.2f}%"

)


print(

    f"TEST TOP-5 ACCURACY: "
    f"{top5 * 100:.2f}%"

)


print(
    "\nBEST MODEL SAVED AT:"
)


print(
    BEST_MODEL_PATH
)


# ============================================================
# 45) CLASSIFICATION REPORT
# ============================================================

target_names = [

    idx_to_class[i]

    for i in range(
        NUM_CLASSES
    )

]


print(
    "\nCLASSIFICATION REPORT\n"
)


print(

    classification_report(

        y_true,

        y_pred,

        labels=list(
            range(
                NUM_CLASSES
            )
        ),

        target_names=target_names,

        zero_division=0

    )

)


# ============================================================
# 46) ACCURACY CURVE
# ============================================================

plt.figure(

    figsize=(10, 5)

)


plt.plot(

    history["train_acc"],

    label="Train Accuracy"

)


plt.plot(

    history["val_acc"],

    label="Validation Accuracy"

)


plt.xlabel(
    "Epoch"
)


plt.ylabel(
    "Accuracy"
)


plt.title(

    "WLASL Training / Validation Accuracy"

)


plt.legend()


plt.grid()


plt.show()


# ============================================================
# 47) LOSS CURVE
# ============================================================

plt.figure(

    figsize=(10, 5)

)


plt.plot(

    history["train_loss"],

    label="Train Loss"

)


plt.plot(

    history["val_loss"],

    label="Validation Loss"

)


plt.xlabel(
    "Epoch"
)


plt.ylabel(
    "Loss"
)


plt.title(

    "WLASL Training / Validation Loss"

)


plt.legend()


plt.grid()


plt.show()


# ============================================================
# 48) PREDICT NEW VIDEO
# ============================================================

def predict_video(

    video_path,

    top_k=5

):

    probs = predict_probs_tta(

        video_path

    )


    values, indices = torch.topk(

        probs,

        k=min(

            top_k,

            NUM_CLASSES

        )

    )


    return [

        (

            idx_to_class[
                i.item()
            ],

            v.item()

        )

        for v, i in zip(

            values,

            indices

        )

    ]


# ============================================================
# 49) FINAL MESSAGE
# ============================================================

print(
    "\n" + "=" * 80
)

print(
    "MODEL READY"
)

print(
    "=" * 80
)


print(

    "Best validation accuracy:",

    f"{best_val * 100:.2f}%"

)


print(

    "Test Top-1:",

    f"{test_acc * 100:.2f}%"

)


print(

    "Test Top-5:",

    f"{top5 * 100:.2f}%"

)


print(
    "\nModel file:"
)


print(
    BEST_MODEL_PATH
)


print(
    "\nTo predict a new video:"
)


print(

    'prediction = predict_video("/content/my_video.mp4")'

)


print(

    'for word, probability in prediction:'

)


print(

    '    print(f"{word}: {probability*100:.2f}%")'

)


print(
    "\nDONE."
)

